import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Realtor Clone Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Home</h1>

    </div>
  )
}
